os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/SanjoDeundiak/f84879af33a270119711bfa333704359/raw/7aee86cffd948568a32745820044ae5cb174ed27/install_swift_linux.sh)"
script:
  - swift build
  - swift build -c release
