os:
  - linux

language: generic

sudo: required

services:
  - docker

dist: trusty

before_install:
  - set -o pipefail

# Build
script:
  - docker build -t "$DOCKER_USERNAME"/wardrobe .

# Build image and push to docker hub
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push sanjodeundiak/wardrobe;
    fi
