os:
  - linux

language: generic

sudo: required

services:
  - docker

dist: trusty

before_install:
  - set -o pipefail

# Build
script:
  - docker build -t "$DOCKER_USERNAME"/wardrobe .

# Build image and push to docker hub
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -;
      sudo apt-get update;
      sudo apt-get install nodejs;
      sudo apt-get install -f;
      sudo apt-get install npm;
      sudo ln -s /usr/bin/nodejs /usr/bin/node;
      sudo npm install -g typescript;
      cd Public; npm install; cd ..;
      ./ts_compile.sh;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push sanjodeundiak/wardrobe;
    fi
